### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by starise** [staniel359/muffon#10]
As soon as possible I'll work on the italian translation, it looks like simple stuff. Hope it'll be appreciated.
Thank you very much for your work, very nice app!

**Comment by staniel359** [comment]
@starise Thanks for your feedback.
Sure, that would be great. If you have any questions on translation, please contact me by my email.

**Comment by staniel359** [comment]
@starise Could you please also address translations here https://github.com/staniel359/muffon/blob/main/electron.js#L54?

**Comment by staniel359** [comment]
@starise Could you please create PR once again? I kind of messed up commits.
