### ISSUE TITLE
I dont like or want to know the names of other  users listening to the Artist.

### ISSUE THREAD

**Issue by oddsito** [staniel359/muffon#103]
------------- Closed

**Comment by staniel359** [comment]
@oddsito Hello.

But you can't see other profiles unless you directly click on `Listeners` counter.
Where else can you see them?

**Comment by oddsito** [comment]
Nah i undertand its ok , its a hobby your app. Nothing to say, Good luck and i wish you a lot of abundance in life. Much Success and Health.

I cant even dream of coding who im i to  say anything? All i can do is understand the psyche of others, their ways.
I have been trying to build your app as an RPM, i can't even do that hahaha. So forget about my opinions, music/sound for me is something very serious, its actually is the most important aspect of existence along with health and strength. 
And ur app simply doesn't reflect the importance and the faculties of music at its best expression. But its close to being perfect... Good job !

**Comment by staniel359** [comment]
@oddsito Thank you!

> And ur app simply doesn't reflect the importance and the faculties of music at its best expression.

So what seems to be the problem?
Any ideas how to make the app better?

**Comment by oddsito** [comment]
Its just that little DETAIL, the tags should be removed. We want to appreciate the artist. Not some Fan made TAGS.
The rest is perfect. In fact this app is 5-10 times faster and more neat - well organized than Nuclear, AudioTube, MellowPlayer, etc this app is better than those other apps, and its closer to perfection than those other apps, its core functionality is very very well polished, but now its just those little details that need tweaking, the TAGS are more part of the UI, are more decorations than anything else.. Perhaps being able to select audio qualities bitrates, would be a plus, but thats related to the servers. I think just the little details like the TAGS, are the only things to tweak, maybe adding themes, what we need to do at this point is advertise it , and make more people use it, so you can get good Donations for your work <3.  Google started being a free search Engine, but through the intense dedication to reach everyone it rose up very high and quickly. 

I for example , i try to share your app as much as possible. Thats how good i think it is.

**Comment by oddsito** [comment]
![image](https://user-images.githubusercontent.com/79411594/236631285-83ec4210-cd30-453b-9db2-728ab3e23c64.png)

![image](https://user-images.githubusercontent.com/79411594/236631483-50f1fc4b-a2e2-4175-8c33-22e95bb5e3d7.png)

![image](https://user-images.githubusercontent.com/79411594/236631768-bf4cca5a-02ea-434b-811e-9d57856a3ac5.png)

![image](https://user-images.githubusercontent.com/79411594/236632127-e5a8cc00-c2ed-46c4-836f-a480fb3a6cb3.png)

These are very interesting TAGS, very good ones, but before the tag would say stuff like "  Muffer, Muffy , Sick DiscoMusic, " It has to change, thank you. It has to look professional, Tags should be official ones. 

![image](https://user-images.githubusercontent.com/79411594/236632051-d8263b9e-ebb1-4a45-b665-a07174b2b26b.png)
But this last one is wrong , those tags are related to you, your friends, family members, thats unrelated to the artist or the music. Someone who is THE USER, the donator, Will feel triggered like i feel, or totally disturbed by those tags. 

Because you know music is about emotions, and people feel many emotions, while using your app. We need to create an environment for the listener that is his OWN environment for his own music. PERSONAL SPACE , where the user feels with himself and the artist, but not Muffer, or Muffon. Thats not included. You only serve as subtle channel, a subtle pathway for the user, but has to remain invisible, subtle, thats why nobody actually wants spotifiy or youtube either for example, or etc service, BECAUSE THE  SERVICE IS TRYING TO OCCUPY TO MUCH SPACE FOR WHAT TRULY MUSIC MEANS,  THE NAME OF THE SERVICE IS NOT THE ARTIST, they're totally unrelated. Thats my opinion as a professional of music . Perhaps they are great businesses but they too fail at grasping the essence  of music, of respecting music and the SPIRIT of music itself, of the artists... etc.. They try to milk people, but we need to help  more than an industry, help the process of healing, of work with the music, and those tags or names are unhelpful for that.  The user needs a personal space where he actually gets to customize or to limit what is he SEEING VISUALLY and what is he listening to..

**Comment by staniel359** [comment]
@oddsito Well, thank you very much. I appreciate it.

 > ![image](https://user-images.githubusercontent.com/18214933/236632532-6b4ebfb5-5e75-4bee-bb0e-10e84821464e.png)

But it's not tags, it's muffon's listeners.
You can just not click on that counter if you don't want to see ones.

I can probably add an option to show/hide this counter if you're suggesting that.

**Comment by oddsito** [comment]
YES that  would be wonderful, an option to " Hide other listeners " it will be good in the future to connect the listeners together, but then we need to also filter, to whom i wanna connect with, what kind of nicknames i want to connect with with an opton of " Hide other listeners " Yes <3. Because maybe im praying with holy shamanic music, and then i read those tags... my prayer is now also directed to you, and thats not what i wanted to read in the middle of my ceremony with music.
So im here sharing my energy with you, but we need to limit how much do i get to absorb , see , share with you, or you with me, Because next nickname can be " Cumblasterinyoface " and im there listening to Frederyk Chopin, its not nice you see? ahahahah .

**Comment by staniel359** [comment]
@oddsito I understand you.
Sometimes I personally don't want to see if someone listens to the same music as I do.
I'll add this feature.

So do you have any issues with tags or just showing other listeners?

**Comment by oddsito** [comment]
Lets Just hide the other listeners sorry yes, and that way when i recommend muffon, why use this app? 

PROS: It respects your privacy, no accounts needed.
        It doesn't impose itself on you with ads, as a service it is free and subtle.
        It is very quick and snappy, and you have more than 28 million songs (to put an example)
        Any kind of listener , artist can easily use it , its intuitive. 
        

It makes use of other paid services, but does their jobs 10 times better, and makes them very free.
Biggest thing that muffon reminds us is that " Music is free "
Perhaps YOU WILL HAVE entities, such as gouverments and artists against you, BUT YOU WILL HAVE ALSO many many people who will back you, like me, the guardians, many other people, who encourage the idea of free music, because IT IS a free tool indeed. People should pay to contribute to music with donations, but music should never be monetized.
1- MAINLY because music is too easy to make and 2- Because it serves as a therapeutic tool that everyone needs.

Today people are lied to with money, but the truth is as it is. We simply contribute to the artists if we can, but we're not forced to. Artists make music of live productions. And recordings are just a way to advertise themselves.
 
 So muffon
 It defeats the other services by doing a better job, offers a better interface. All for free really. The day you wanna monetize, you will adapt your own methods. But so far those little details count yeah : D , yes its interesting , maybe one day you wanna see who listens to the same music as you -- You enable the option, "See other listeners" . Some day you wake up, you dont wanna see it? "Hide other listeners" Thats it <3 

Perhaps you can do something that hasn't been done in other apps, allow " Messaging other users " , you can enable the option to message others, who knows. You are the genius programmer hahahah. But these can be good options. Eventually it can be a social-media of music listeners who share together. You have so many options, i know its all related to how well you can program, because i've tried to do it in the past and its hard, requires dedication. We must always acknowledge your skills. Thank you for your work, i will donate someday soon for example.Im getting my creditcard fixed, in a few months i would like to donate. Its 10 times better than spotify or youtube music.

**Comment by staniel359** [comment]
@oddsito Again, thank you very much.
It's always nice to know that someone likes your work.
And you make a good point about music and its monetizing.
But money is a large and tough question, though.
So much to think of and consider.

Well, the app is free because I can't capitalize on something I also get for free.
Basically muffon plays the same music that you can listen in your browser via Spotify, Deezer, Yandex Music, etc.
What actually costs is my time, effort and server hosting.
But I'm not making anyone to pay.
I hope there'll be donations in the future.

**Comment by oddsito** [comment]
We're skipping the ads with it, better interface ! incredible work. You are the only one doing it for free. The other companies actually want you to pay, with your interface we skip that option hmm !

**Comment by staniel359** [comment]
@oddsito Yes, ads are the worst.
