### ISSUE TITLE
Support for Apple chip

### ISSUE THREAD

**Issue by bambooom** [staniel359/muffon#104]
I'm using Apple MacBook Pro with Apple M1 pro chip. 
But it shows "not supported" on the website.
Is it possible to support it in the future?

Thanks.

**Comment by staniel359** [comment]
@bambooom Hello.

>  But it shows "not supported" on the website.

That's weird.
Could you open your browser's DevTools, then open console tab, enter
```js
navigator.userAgentData?.platform
```
and
```js
navigator.platform
```
and send me the result?

**Comment by bambooom** [comment]
```
> navigator.userAgentData?.platform
'macOS'
> navigator.platform
'MacIntel'
```

The result is like this.
I'm using Chrome version 114.0.5735.106 (Official Build) (arm64)

**Comment by staniel359** [comment]
@bambooom Thanks.
Found the problem.
Please check the site now. There should be the arm64 version for macOS.

**Comment by bambooom** [comment]
I've checked the site and it's fixed. Thanks!

**Comment by staniel359** [comment]
@bambooom You're welcome!
