### ISSUE TITLE
Flatpak support

### ISSUE THREAD

**Issue by skobkin** [staniel359/muffon#106]
Currently there are very limited set of app packages for Linux.

To make it more widely known and make installation on any distribution easier, I'd suggest to add [Flatpak](https://github.com/flathub/flathub/wiki/App-Requirements) support and publish it on [Flathub](https://github.com/flathub/flathub/wiki/App-Submission).

**Comment by staniel359** [comment]
@skobkin Hello.
I can add Flatpak version to releases, but I don't know if it should be published to Flathub.
I personally don't publish the app anywhere else except GitHub as it would be harder for me to maintain all the platforms.
In that case this should also be published to Mac App Store, which is quite complicated, I suppose.
So I simply deal only with GitHub.

**Comment by skobkin** [comment]
It'd be better than nothing.
But I'm not sure if it's really impossible to publish releases using Github Actions.

**Comment by staniel359** [comment]
@skobkin It's possible:
https://www.electron.build/configuration/publish.html
https://github.com/staniel359/muffon/releases

**Comment by skobkin** [comment]
@staniel359 I don't see how it's related to Flathub, but if you're sure that it's possible, then I don't see a reason why not to do that :shrug:

UPD: I mean publishing releases to Flathub of course.

**Comment by staniel359** [comment]
@skobkin Sorry, misunderstood you.

I'll add a Flatpack version anyway, and maybe someone will publish it to Flathub.

**Comment by skobkin** [comment]
@staniel359 As far as I understood, they're not very fond of packages published not by authors.
So I'm not sure if it'll be allowed. But we'll see.

**Comment by staniel359** [comment]
@skobkin I see. Thanks for the information.
