### ISSUE TITLE
Won't start on arch

### ISSUE THREAD

**Issue by dillfrescott** [staniel359/muffon#109]
I installed it and it just doesn't open at all :(

Any ideas?

I tried running `/opt/muffon/muffon` directly even with `sudo` and it just says core dumped

**Comment by staniel359** [comment]
@dillfrescott Hello.
Have you allowed it as executable?

**Comment by dillfrescott** [comment]
I would think so because I installed it via Pacman. I can double check though

**Comment by staniel359** [comment]
@dillfrescott Maybe it's the issue with Pacman.
Try downloading and installing it from [here](https://github.com/staniel359/muffon/releases/tag/v1.6.0).

**Comment by dillfrescott** [comment]
Okay

**Comment by staniel359** [comment]
@dillfrescott Did it work?

**Comment by dillfrescott** [comment]
Yes, just tested it and it seems to work! How weird! Ill close this now
