### ISSUE TITLE
YouTube and YouTube Music stopped working

### ISSUE THREAD

**Issue by nyouness** [staniel359/muffon#110]
Hii , thank you for making this cool project , my issue is yesterday youtube and youtube music was working fine but today is not working , i've tried uninstalling and installing Muffon again 3 times and i tried continue anonymously but wont work , this is what it gives me :

![1](https://github.com/staniel359/muffon/assets/117232906/6c954736-2e8b-4387-8200-93d78d49f3c3)
![2](https://github.com/staniel359/muffon/assets/117232906/8e03c557-83a4-4e67-99dd-9d3582ec17ee)
![3](https://github.com/staniel359/muffon/assets/117232906/90d2aaab-0d5e-4081-823b-7a99c3846014)

**Comment by staniel359** [comment]
@nyouness Hello.
I don't know what happened, but somehow YouTube daily requests limit of 10000 has been exceeded.
I hope tomorrow it'll be working again.

**Comment by nyouness** [comment]
I hope , and thanks again!

**Comment by staniel359** [comment]
@nyouness You're welcome!

**Comment by staniel359** [comment]
@nyouness Closing as it's working again.

**Comment by nyouness** [comment]
Hii again , i don't know if im the only one who is having this problem but all of the providers not working except YouTube videos , i tried to play couple of songs but nothing is working for me , when pressing VK or any providers nothing is happen : 

![Screenshot 2023-08-06 114204](https://github.com/staniel359/muffon/assets/117232906/bd0de926-ee6f-4eea-a235-91d859b13e0b)
![Screenshot 2023-08-06 114243](https://github.com/staniel359/muffon/assets/117232906/10b14314-fc60-4bd9-9d9e-a2ef1e696c3f)
![Screenshot 2023-08-06 114343](https://github.com/staniel359/muffon/assets/117232906/7a998549-8f4b-4837-bc79-a3e8443c1bad)

**Comment by nyouness** [comment]
![Screenshot 2023-08-06 121422](https://github.com/staniel359/muffon/assets/117232906/64605222-1cea-4e63-9233-8c839550ac26)

songs wont play and lyrics wont work

**Comment by staniel359** [comment]
@nyouness Thanks for reporting.
That's a server's wrong proxy issue.
Again, I have no idea why it has been changed.
Should be working now.

**Comment by nyouness** [comment]
Thanks a loot its working perfect , happy to help!
