### ISSUE TITLE
The search results obstruct the playlist modal window

### ISSUE THREAD

**Issue by adinan-cenci** [staniel359/muffon#111]
Hello. I am loving the app. Just want to report this bug.

## Steps to reproduce
1. Click on the search bar and search for a track.
3. Once the results load, pick one and click on the three dots button -> Add to playlist.
4. The playlist menu will open, but it will be obstructed by the search results.

[Kooha-2023-08-06-08-35-59.webm](https://github.com/staniel359/muffon/assets/1629643/d4d4f06a-c579-4238-b13e-9aae52da2513)

**Comment by staniel359** [comment]
@adinan-cenci Hello.
Thanks for the good reproduction.

It's a known bug, which has already been fixed.
You'll see the changes in the next version.
