### ISSUE TITLE
docker images support？

### ISSUE THREAD

**Issue by sikenali** [staniel359/muffon#112]

**Comment by staniel359** [comment]
@gegewuwuwu Hello.
Could you give more details?

**Comment by sikenali** [comment]
> @gegewuwuwu Hello. Could you give more details?

I want to deploy this application to my NAS device.

**Comment by staniel359** [comment]
@gegewuwuwu Sorry, the server is centralized.
See https://en.wikipedia.org/wiki/Single_source_of_truth.
