### ISSUE TITLE
Problem when closing a tab. 

### ISSUE THREAD

**Issue by nortmas** [staniel359/muffon#124]
It's quite difficult to catch the "close" button when I want to close a tab. (please watch the video)

https://github.com/staniel359/muffon/assets/1155719/bbedcc43-5746-4bcf-ac97-2bc061c4a265

It would be great to find a solution and fix it. Thank you!

As an option maybe just show the tab name in the tooltip without expanding to the right.

**Comment by staniel359** [comment]
@nortmas Got it, thanks.
