### ISSUE TITLE
The app cannot be closed on Mac.

### ISSUE THREAD

**Issue by nortmas** [staniel359/muffon#125]
When I try to quit from the app on mac OS 14.1 (M2), it doesn't work. Only the "force quit" helps.

**Comment by staniel359** [comment]
@nortmas Have you tried this option?

![image](https://github.com/staniel359/muffon/assets/18214933/f1652066-af68-4ce3-be59-fceee29183d7)

**Comment by nortmas** [comment]
Yes, it works! Thank you!
