### ISSUE TITLE
Not clear where we are registering.

### ISSUE THREAD

**Issue by bonelifer** [staniel359/muffon#127]
Not clear where we are registering.

**Comment by staniel359** [comment]
@bonelifer What do you mean "where"?

**Comment by bonelifer** [comment]
I assume this was a desktop app. it has login page. is that some local thing or is that for a website?

**Comment by staniel359** [comment]
@bonelifer It's for account creation.

**Comment by bonelifer** [comment]
where am I making this account? this is the first I have heard of this app, so I dont know anything about it.

**Comment by staniel359** [comment]
@bonelifer On a remote server.
You can use anonymous mode if you want.
