### ISSUE TITLE
[Question] Is there a command line support?

### ISSUE THREAD

**Issue by versor2k7** [staniel359/muffon#128]
Hi there, is there a command line support for muffon? I'm asking because I want to build an music box like TigerBox for our child, but without the limitation to only use their products.
For this I would like to (maybe) play predefined playlists via command line (after placing an RFID-card on the box).

Thanks in advance. Best wishes, versor

**Comment by xyloflake** [comment]
No, muffon desktop client is the only client we have as of right now. CLI support was never planned and I don’t think it ever will be.

We can probably suggest something for your use case. Please hop on to the discord server if you wish to continue this conversation!

Regards,
Xylo,
Admin and Developer at muffon

**Comment by versor2k7** [comment]
Thanks for the real time response :) 
So my search must go on. But I will keep your package, because I like it even without CLI :-D

**Comment by xyloflake** [comment]
@staniel359 this needs to be closed as not planned.
