### ISSUE TITLE
[Integration] - Spotify integration doesn't work, says Forbidden

### ISSUE THREAD

**Issue by sstvskids** [staniel359/muffon#134]
![image](https://github.com/staniel359/muffon/assets/126665568/9b86cdeb-99a8-459a-bc8b-51c60ba2ab89)

Spotify link wont work, paste in the code, forbidden access.

**Comment by xyloflake** [comment]
Hello! We haven’t been approved by Spotify for using their oAuth (yet). So it’s expected. It’s also mentioned in the readme that it is a coming soon feature.

Happy new year!

Xylo, 
Admin and Developer at muffon

**Comment by xyloflake** [comment]
@gamersi will be addressing your concern.

Xylo,
Admin and Developer at muffon.

**Comment by gamersi** [comment]
Hello sstvskids,
Thank you for reporting your findings!
Sadly, Spotify declined our application, but we are currently talking to them about what can be done to fix it.
Please keep in mind that this process is time consuming so it may take a while to find a deal.

We will close this issue soon. If you have other questions, feel free to open a new issue and/or join our [discord server](https://discord.gg/kpWsA5NBmJ) to report bugs and get the latest news.

Also, the development is currently pretty slow, as all the devs are busy at the moment. You can still expect updates regularly.

Have a nice start into 2024,
Simon | gamersi (Dev & Admin at muffon)

**Comment by xyloflake** [comment]
Actually, thinking back at it, let's keep this issue opened until Spotify approves

**Comment by f0086** [comment]
Any update on this? Still not working :(

**Comment by staniel359** [comment]
@f0086 Will be fixed in the next version.

**Comment by xyloflake** [comment]
@f0086 we recently announced on our [discord server](https://discord.gg/mqTfSWSS) about the latest news involving Spotify. Consider joining for being up to date.

![image](https://github.com/staniel359/muffon/assets/142194553/aa67bb74-f36c-499c-a3d6-94f546ba1574)

**Comment by xyloflake** [comment]
Hey guys, just an update here. We've beta tested the release. First beta was successful and we found some bugs which are now fixed. Spotify Integration will be completely working in the next release @f0086 @sstvskids

**Comment by xyloflake** [comment]
We've finally solved this! Enjoy version 2.0.3! Spotify integration is now working.

# Closing as solved
