### ISSUE TITLE
Soundcloud error: 403 - This content is only available on SoundCloud

### ISSUE THREAD

**Issue by ghost** [staniel359/muffon#144]
it can search tracks etc but does not play songs on arch linux.

**Comment by xyloflake** [comment]
Thank you for opening an issue. Our Linux expert and admin @gamersi will be in your service.

**Comment by gamersi** [comment]
Hello
Are you using Pipewire or pulseaudio?
Are you using the AUR package or the downloaded .pacman?

**Comment by ghost** [comment]
aur package, pipewire @gamersi

**Comment by gamersi** [comment]
Do other electron / chromium based applications work?

**Comment by ghost** [comment]
@gamersi I mean there were no problem on msedge

**Comment by staniel359** [comment]
@toprak Hello.
@xyloflake @gamersi It doesn't have anything to do with Linux.

**Comment by staniel359** [comment]
@toprak Hello.
All songs?

**Comment by ghost** [comment]
@staniel359 vk works, soundcloud does not work on any song

**Comment by gamersi** [comment]
then it’s either a bug in muffon or it is about audiocodecs

**Comment by xyloflake** [comment]
@toprak is Soundcloud, by any chance, blocked in your country?

**Comment by ghost** [comment]
@xyloflake i can listen songs on soundcloud with microsoft edge

**Comment by xyloflake** [comment]
@toprak I wantchu to join our [discord server](https://discord.gg/dj2pykja) and contact us for testing a beta release. Please do as instructed ASAP.

**Comment by staniel359** [comment]
@toprak Provided audios didn't work for me either, but other SoundCloud audios did.
I suppose it's country restictions issue again.
(App's server is in UK).
Will try to handle this.

**Comment by xyloflake** [comment]
Changing assignment of @gamersi to @staniel359 because this is not a Linux issue as per the [video](https://streamable.com/i4r1lz) @toprak provided. 

Problem is with SoundCloud as per the [image](https://cdn.discordapp.com/attachments/1197976745995948082/1198002142313726002/image.png?ex=65bd5170&is=65aadc70&hm=dc6662f9af5ebed2b5e414dedc4cbfd322a54704d4751da6fca699795afa3e45&) @staniel359 sent.

**Comment by staniel359** [comment]
@toprak Should be working now.

**Comment by xyloflake** [comment]
@toprak has confirmed that the fix indeed works. Thanks Staniel!
