### ISSUE TITLE
No way to scroll tabs if they don't fit in the tabs bar length.

### ISSUE THREAD

**Issue by dmitry-buzzwoo** [staniel359/muffon#147]
![Screenshot 2024-01-25 at 10 30 51](https://github.com/staniel359/muffon/assets/140138846/2980973c-2ceb-4154-845c-b16edf3c42ff)

**Comment by xyloflake** [comment]
We are aware of that. Thanks for reporting. The fix is planned.

**Comment by staniel359** [comment]
@dmitry-buzzwoo Hello.
Please use `Shift + Mousescroll` when mouse is on tabs panel.
