### ISSUE TITLE
Turkish Translation

### ISSUE THREAD

**Issue by hbasaraner** [staniel359/muffon#149]
I want to add Turkish language support to the app. Someone is shared this app in  [eksisozluk.com](https://eksisozluk.com/entry/161049724) -which is one of the most popular websites in Türkiye-, so Turkish users might be interested for this app.

**Comment by xyloflake** [comment]
Thank you for making an issue in the muffon repo! We whole-heartedly welcome you to the muffon community. 

To make a translation contribution, you’ll have to join our [discord server](https://discord.gg/kwdm3Vrm) and ping an Admin there for access to localization resources access. From there, @staniel359 will guide you.

Thanks a lot for being interested in contributing to the repo! See you in the discord server :)

> [!NOTE]
> Translating is a very long and hectic process, please make sure you’re ready to handle all of it. We appreciate your help!
