### ISSUE TITLE
Music.app is activated on pressing multimedia keys.

### ISSUE THREAD

**Issue by dayfuaim** [staniel359/muffon#151]
Pressing multimedia keys on keyboard outside (and inside) `muffon` activates Music.app instead of playing/pausing/etc.

Версия 2.0.2 (2.0.2)

**Comment by gamersi** [comment]
Are you on macos?

**Comment by dayfuaim** [comment]
Yep.
macOS Sonoma, MacBook Pro M1

**Comment by staniel359** [comment]
@dayfuaim Got it, thanks.

**Comment by xyloflake** [comment]
@staniel359 this is NOT a bug, please consider asking me before jumping to a conclusion.

As stated by electron in https://www.electronjs.org/docs/latest/api/global-shortcut

> The following accelerators will not be registered successfully on macOS 10.14 Mojave unless the app has been authorized as a [trusted accessibility client](https://developer.apple.com/documentation/accessibility/accessibility-inspector):
> - "Media Play/Pause"
> - "Media Next Track"
> - "Media Previous Track"
> - "Media Stop"

**Comment by xyloflake** [comment]
Hey @dayfuaim I need you to join our [discord server](https://discord.gg/TmFujW8B), we need you to beta test when we release a beta fix.

**Comment by xyloflake** [comment]
Even if this is not a bug, please let this be open, I’ll try a fix.

**Comment by xyloflake** [comment]
@staniel359 requesting my assignment on this issue.

**Comment by staniel359** [comment]
@xyloflake
> this is NOT a bug, please consider asking me before jumping to a conclusion.

Sorry.

**Comment by gamersi** [comment]
Hello,
Sadly, I can't reproduce this issue on my MBP 2019 with touchbar on MacOS Sonoma
Have you found any fix or possible cause for it?

**Comment by xyloflake** [comment]
@dayfuaim we've tested this on a mac and it seems like it runs okay, If you still can't play using the media keys, please try using the video I'm linking below.

Watch [this](https://www.youtube.com/watch?v=DYZ6F11vGjo) super nice tutorial on how to give apps access to accessibility and once you do it, it should provide muffon permissions to interact with the media controls.

As you can see in the video below, @gamersi tried it on his MacBook Pro 2019 with a touch bar, and it works perfectly fine.

https://github.com/staniel359/muffon/assets/142194553/2dee61f9-174d-4684-b2f6-ea75134b03e2

**Comment by xyloflake** [comment]
We're closing this as no one has been able to reproduce this and OP has been inactive
