### ISSUE TITLE
Empty radio screen

### ISSUE THREAD

**Issue by zefir1990** [staniel359/muffon#156]
Installed for Arch Linux via yay (AUR), see empty Radio screen
![Screenshot_20240402_104716](https://github.com/staniel359/muffon/assets/19148646/647f974b-fb29-458e-8c46-bc0b5144bd7a)

**Comment by xyloflake** [comment]
Hi @demensdeum ! Thanks for taking the time to make an issue :D

We wholeheartedly welcome you to muffon.

As for the issue, this is not a bug, in fact you have to choose the source of the radio by clicking this
![image](https://github.com/staniel359/muffon/assets/142194553/1f060e2c-efd3-4c5c-862d-90ddfe5b93bf)
and selecting "Artists" or "Tracks".
![image](https://github.com/staniel359/muffon/assets/142194553/7a392403-f234-4a24-8e9d-2a6ef48611d3)


You can also hover over "top" and see a menu containing "tag" and "artist". You can try selecting them and searching your fav. tag or artist and it'll play radio based on that.
![image](https://github.com/staniel359/muffon/assets/142194553/545cd5f6-4cc5-4078-a441-7135e4d7ece5)

We hope you have a great day ahead!

**Comment by staniel359** [comment]
@demensdeum And it doesn't have anything to do with Arch Linux, obviously.

**Comment by zefir1990** [comment]
Thanks guys, I use Arch btw

**Comment by zefir1990** [comment]
I thought it's web radio, like "Radio Maximum" for example
