### ISSUE TITLE
Suggestion: Retire Bookmarks/Favorites in favor of Tiers within the Library and filter for content type

### ISSUE THREAD

**Issue by chrislowles** [staniel359/muffon#175]
I feel like UX-wise people could be confused as to whether they should use Bookmarks/Faves or add to their Library when trying to move over and I think using tiers in a unified library system would be better for organization and overall UX, without losing the detail of "For later" in something like Bookmarks and "Actual Favorites" in something like a Favorited item. This would require a filter for content types like videos too so I guess that should be mentioned. Sorry this is a bit of a heavy suggestion I just really want this to succeed so I can finally ditch YTM and Spotify lol

**Comment by xyloflake** [comment]
You can help with UX. We currently don't have people who know much UX. I mostly do backend and so do the others. If you'd like to have a chat with us, please join the discord server.

Thanks for the suggestion @chrishazfun

**Comment by staniel359** [comment]
@chrishazfun Hello.

The logic is:
1. **Library** - for your collection (also basis for recommendations). Seen by everyone.
2. **Favorites** - obviously your favorite items (not everything from your library is your favorite). Seen by everyone. Also has separate section for quick access.
3. **Bookmarks** - for later. Seen only by you.

I don't think it's confusing.

**Comment by staniel359** [comment]
@chrishazfun @xyloflake I think I will close this and add the instruction for current functionality someday.
