### ISSUE TITLE
[Integrations] [Spotify] Imported Playlist Timestamp set to Import Time Instead of Creation Date

### ISSUE THREAD

**Issue by mzmonkey** [staniel359/muffon#182]
When importing playlists from Spotify, the displayed time for playlists is the time of the import and not the time the playlists were created.

Given:
Playlist created 03.05.2022
Imported 29.06.2024

Expected 03.05.2022, but got 29.06.2024

Btw importing time and dates for unique songs works perfectly fine but not for playlists.

**Comment by staniel359** [comment]
@MikaHD666 Hello.
Thanks, will look.

**Comment by staniel359** [comment]
@MikaHD666 Could you tell where did you get playlists's creation date?
Or maybe provide a link to it?
