### ISSUE TITLE
Add offline feature

### ISSUE THREAD

**Issue by robin98** [staniel359/muffon#2]
Hi,
This is so good. but it is great if you add offline / download as .mp3 capability.
Thanks.

**Comment by staniel359** [comment]
@robin98 Could you please explain in details how are you expecting this feature to work?

**Comment by dm9pZCAq** [comment]
may be add option to download tracks, albums or full artist discography?

for example by right click on track and than press `download` button

or add `download` button near `play`

**Comment by staniel359** [comment]
@dm9pZCAq Sorry, no downloads. It may cause legal troubles.

**Comment by robin98** [comment]
> @dm9pZCAq Sorry, no downloads. It may cause legal troubles.

This is so bad. at least you can make an offline playlists, so users still be able to listening to the music while they can't access the internet, just like Spotify app.

**Comment by staniel359** [comment]
@robin98 It would be quite complicated to achieve.
For Spotify if you save song for offline, it saves one particular song from one source. But here you don't have songs, but tracks, which have multiple versions of song from different sources.
One option can be choosing the track song (variant) and then save it for offline, but only when that song is playing. In that case it can be done, but in the future and if this feature finds support from other users.

**Comment by robin98** [comment]
> @robin98 It would be quite complicated to achieve.
> For Spotify if you save song for offline, it saves one particular song from one source. But here you don't have songs, but tracks, which have multiple versions of song from different sources.
> One option can be choosing the track song (variant) and then save it for offline, but only when that song is playing. In that case it can be done, but in the future and if this feature finds support from other users.

You may create a separate extension for the muffon that add Download feature to it.
This is how if any legal problem happenes, it’s just about that certain extension, not your whole project ;) (It could be like an 3rd party extension)

**Comment by staniel359** [comment]
@robin98 Okay, I think, we'll figure this out in the future.

**Comment by boehs** [comment]
It's quite easy to download music via youtube

**Comment by staniel359** [comment]
@boehs It is. But it is legal?

**Comment by staniel359** [comment]
@robin98 Is this still relevant? What's the purpose of offline listening?

**Comment by boehs** [comment]
> @boehs It is. But it is legal?

Probably, but consider

1. If it is, this project is also. Streaming music is obtaining a copy, and you don't have the copyright holder's consent.
2. YoutubeDL was taken down on the grounds of DMCA but quickly restored because it was BS. Perhaps there is an angle, but the RIAA is too dumb, too lazy, or it just does not exist. Perhaps a combo of both
3. A defense is some music you do have the right to download, such as that in the public domain
4. A module/plugin that does this would lower the surface for attack

 >  Is this still relevant? What's the purpose of offline listening?

I syncthing to my phone and then during long train rides vibe

**Comment by staniel359** [comment]
@boehs
> I syncthing to my phone and then during long train rides vibe

But it's a desktop app.

So what's exactly your point on downloading? I didn't seem to get it.
For me it's not so legal comparing to just listening.

**Comment by bytezeroseven** [comment]
I was wondering if the Spotify API provided by muffon can be used in my personal project. 
1. There isn't any CORS restriction on the API, will that be like that forever?
2. Will the spotify audio link API stay forever?

**Comment by staniel359** [comment]
@bytezeroseven Hello.
How does that relate to this issue?

**Comment by bytezeroseven** [comment]
@staniel359 It doesn't. I was just trying to ask a question 😅

**Comment by staniel359** [comment]
@bytezeroseven Please create separate issue for your questions. Thanks.

**Comment by bytezeroseven** [comment]
@staniel359 here it is: https://github.com/staniel359/muffon/issues/54
