### ISSUE TITLE
Playlist Cover

### ISSUE THREAD

**Issue by magellandi** [staniel359/muffon#24]
Hello there!
We can't add the photo cover to the playlist.
Please fix it.

Thank you.

**Comment by staniel359** [comment]
@magellandi Hello there.
What's the format of the image you're trying to upload?

**Comment by magellandi** [comment]
> 

I double-checked everything. Although the error message clearly shows that the photo was not added, it is eventually added.

This software is incredible! 
I used it all day and told others about it.

**Comment by staniel359** [comment]
@magellandi Could you make a screenshot of an error?

Well, thanks for your feedback.

**Comment by staniel359** [comment]
@magellandi As long as there's no response, I close the issue.
