### ISSUE TITLE
JavaScript error occurred in the main process - macOS

### ISSUE THREAD

**Issue by arefrafei92** [staniel359/muffon#27]
There is an error before playing music and in the start of app, it prevents app from going next music unless click on ok

<img width="372" alt="image" src="https://user-images.githubusercontent.com/8364557/147747027-ad9c7c58-e532-427f-8b73-f9988a7b3edd.png">

**Comment by staniel359** [comment]
@z85510 Hello.
Got it. Will be fixed in the next version.

**Comment by staniel359** [comment]
@z85510 Could you download new version and check for the bug again?

**Comment by arefrafei92** [comment]
<img width="372" alt="image" src="https://user-images.githubusercontent.com/8364557/147786044-da53470a-7715-4d82-bf41-33854876f39d.png">
This happens in start, and now nothing work in app and search doesn't work , in the previous version there were some error in start and before playing every music but after clicking on ok it was working but now I can't even find a music to play

**Comment by staniel359** [comment]
@z85510 That's weird.
The problem is with the tray. Do you see app icon in system's tray?

**Comment by staniel359** [comment]
@z85510 Okay, I've made changes. Try downloading 0.1.0-beta again.

**Comment by arefrafei92** [comment]
It works perfectly, great job ✌🏼

**Comment by staniel359** [comment]
@z85510 You're welcome.
