### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by AlirezaHC** [staniel359/muffon#3]
are servers down ?

**Comment by staniel359** [comment]
@AlirezaHC Yes, temporarily.

**Comment by staniel359** [comment]
@AlirezaHC Should be working now.

**Comment by Six6Be** [comment]
hi, not working

**Comment by staniel359** [comment]
@Six6Be @AlirezaHC Sorry, folks, forgot to restart server. **Now** it should be working.
