### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by arefrafei92** [staniel359/muffon#31]
Add ability to go next page when it reaches end of list and also add feature to change item per page count.

Make android/ios version as well or web app

**Comment by staniel359** [comment]
@z85510
> Add ability to go next page when it reaches end of list

You mean infinite scroll?

> Make android/ios version as well or web app

Frankly, I didn't plan to make one of those.

**Comment by arefrafei92** [comment]
Yes, infinite scroll can bring better UX.
If you need to make smartphone application I can help with it , I'm flutter developer

**Comment by staniel359** [comment]
@z85510 Then infinite scroll will be as an option.

And what to mobile app: let's put aside this question for now.
I wanted to finish desktop one first.
But I appreciate your help, very nice of you.
