### ISSUE TITLE
Reset Password

### ISSUE THREAD

**Issue by Galladean** [staniel359/muffon#32]
Hi, I recently found the program just before the beta was released and was extensively using it at the time. Recently I had to reinstall all programs after a format and realised I don't remember the password to my account. I couldn't find any references on how to recover my account in the event I do forget and although its fairly easy to make a new account its a hassle to find all the songs again. Can you let me know how I can recover my account?

**Comment by staniel359** [comment]
@Galladean Hello.
Right now there's unfortunately no way to reset your password, but I will add this feature.
Meanwhile you may send me your email that you used for sign up and your new (temporary) password to staniel359@gmail.com and I will change it on the server.
After login you may change that password again.
