### ISSUE TITLE
Cannot sign up

### ISSUE THREAD

**Issue by Borewit** [staniel359/muffon#34]
I wanted run the application from my dev enviroment to figure out if [music-metadata](https://github.com/Borewit/music-metadata) could be an interesting alternative for jsmediatags.

I cannot create an account, is your server maybe down @staniel359?

![image](https://user-images.githubusercontent.com/23255260/148840402-3c2384df-c68f-48f6-8943-9e3a901e65c5.png)

**Comment by staniel359** [comment]
@Borewit Hello.
You don't have a development server running.
You should switch to production one as seen [here](https://github.com/staniel359/muffon/blob/main/src/main.js#L16).

**Comment by Borewit** [comment]
Connecting to `https://muffon.endorphine.by` works, the application looks amazing!

So how do I start a local server back-end? Is that `yarn run start`, which listens to HTTP/TCP port 3000?

**Comment by staniel359** [comment]
@Borewit It requires Ruby and [this repo](https://github.com/staniel359/muffon-api).
But you probably wouldn't want to do that.

**Comment by Borewit** [comment]
Understood, thanks @staniel359!

> But you probably wouldn't want to do that.

No, I think you are right, but good to know.
