### ISSUE TITLE
Add the ability to subscribe and create playlists (Like in NewPipe)

### ISSUE THREAD

**Issue by grishiit** [staniel359/muffon#4]
Hello,
This is only alpha, but already works great. It would be nice to add the ability to make playlists (or save existing ones) and subscribe to the artists you want. It is even possible to separately add a section with "liked" tracks (preferably with its specific variant from a specific source).
Thanks.

**Comment by staniel359** [comment]
@Ilyaandro Hello and thanks for the feedback.

What to playlists - it is a planned feature, it will be implemented in near future.
What to liked tracks - it will be as well, but maybe a little bit later.
What to artists' subscriptions - could you please explain in details how do you want it to work?

**Comment by grishiit** [comment]
@staniel359 Ideally, there would be a feed tab with new songs from the artists you follow.

But, if this is too difficult to implement, it would be nice to just have a tab for quick access to the profiles of your favorite artists.

**Comment by staniel359** [comment]
@Ilyaandro I think it will be possible. Just a matter of time.

**Comment by staniel359** [comment]
@Ilyaandro Hello.
Seems like none of the services the app uses actually provide access to new tracks information.
