### ISSUE TITLE
last.fm Bad Request after allowing

### ISSUE THREAD

**Issue by debpalash** [staniel359/muffon#43]
![image](https://user-images.githubusercontent.com/4178343/154839148-26d2c02d-4b49-4a1e-8bc6-99e694363410.png)

**Comment by staniel359** [comment]
@debpalash Hello.
Fixed. Check it please.

**Comment by debpalash** [comment]
> @debpalash Hello. Fixed. Check it please.

Sure. Thanks
Works smoothly :)
