### ISSUE TITLE
please provide this feature...

### ISSUE THREAD

**Issue by eriksenmarshal** [staniel359/muffon#44]
im using  this app almost every day and thank u very much for creating it... i just wanted to suggest creating a share button to share our playlists or favorite songs with others. just like other streaming platforms like deezer or spotify, they allow user to copy the link of a track, album, playlist and... please make this option available
thanks

**Comment by staniel359** [comment]
@eriksenmarshal Hello.
There's already an issue of you (#6).
I saw it, it'll be implemented in future.
