### ISSUE TITLE
Infinity search

### ISSUE THREAD

**Issue by voy22** [staniel359/muffon#45]
Hello Akeksey
Glad to see this amazing product.
But i see some bugs
1) Infinity search
<img width="1137" alt="image" src="https://user-images.githubusercontent.com/25362701/155526969-e46a6d1b-9957-4771-85b4-e0fedede6191.png">

2) I closed the app and some track still playing and it is still in systray.
Even "Quit" doesn't helps me
<img width="172" alt="image" src="https://user-images.githubusercontent.com/25362701/155527560-ad6e5439-f113-44c0-936c-cf23193dc2cd.png">

Maybe it depends on point 1)

Did it twice - same result.

Good Luck!

**Comment by staniel359** [comment]
@voy22 Hello. 
I just tried it myself.
The search is working and the app closes on 'Quit' and music stops.
Does the problem still persist?
