### ISSUE TITLE
can't import library from last.fm

### ISSUE THREAD

**Issue by maxsubs** [staniel359/muffon#49]
after linking my last.fm account, I've tried to import my library, but I'm getting this error "Forbidden
You don't have rights to perform this action". Muffon shows as "connected" on lastfm/settings/applications, so I don't really know if it's a bug or something else.

**Comment by staniel359** [comment]
@maxsubs Hello.
When exactly do you get this message?

**Comment by maxsubs** [comment]
when I go to Library/add to library/from account/ and click on the red button "import last.fm data" then I get to see my lastfm username and number of scrobbles to import (51.010) and get this error, the progress bar doesn't move and beneath is loading...

**Comment by staniel359** [comment]
@maxsubs
That's weird. It's working with my account.
What's your Last.FM nickname?

**Comment by maxsubs** [comment]
maxif875, may it be too many data to import?

**Comment by maxsubs** [comment]
it's not scrobbling from my local library to lastfm either, so it's something wrong with the connection with lastfm, just checked it if scroblings were working

**Comment by staniel359** [comment]
@maxsubs Seems like it's Last.FM error.
When I try to get your scrobbles, it returns:
`Login: User required to be logged in`

**Comment by maxsubs** [comment]
wait, I don't get it, how can you get my scrobbles without connecting first to lastfm on settings/services, if I don't link my lastfm account first, the button "add library from account" is greyed out. And for that you need my password. Where are you getting that message?

**Comment by staniel359** [comment]
@maxsubs Don't worry, I didn't use your account.
Here's the link to your Last.FM scrobbles:
https://ws.audioscrobbler.com/2.0/?method=user.getRecentTracks&user=maxif875&api_key=fb914bd85f85f89d750e93c8bfb70012&format=json

**Comment by staniel359** [comment]
@maxsubs I've just asked Last.FM support about this.
That's weird, this error is not even documented.
Will wait for response.

**Comment by maxsubs** [comment]
sorry didn't mean that, I was just curious. Now that I see the link I see it's about recent songs, which I had disable on lastfm/settings/privacy/"Hide recent listening information" if I make this public, so Muffon can now retrieve my library, so
SOLVED! thanks for the assistance and for the great software!

**Comment by maxsubs** [comment]
maybe it'd be good to show a warning to make your recent songs public for it to work. I thought since I had my account linked with my password and all that it didn't matter

**Comment by staniel359** [comment]
@maxsubs Good.
Didn't know that scrobbles should be shown to be imported.

`> maybe it'd be good to show a warning to make your recent songs public for it to work`
Good idea. I'll make a message about it.

And you're welcome.
