### ISSUE TITLE
Use with out registering 

### ISSUE THREAD

**Issue by cyberofficial** [staniel359/muffon#52]
Any way to use with out signing up/in?

**Comment by staniel359** [comment]
@cyberofficial Hello.
Sorry, there's no such option.
You can use fake email, though.

**Comment by premek** [comment]
what is the account and the email used to? I was also not expecting needing to log in on my first use. Maybe add the answer to this question to the login/singnup screen for the first time users like me

**Comment by staniel359** [comment]
@premek Hello.
It is used for tracking users count and for most of the features described [here](https://github.com/staniel359/muffon#features).

I think it's common practice for Web applications to require sign up.
Why should it be explained?

**Comment by premek** [comment]
yes but it's unexpected for desktop apps, at least for me.
But please don't take this as a criticism, I just wanted to give feedback.

**Comment by staniel359** [comment]
@premek Sometimes desktop app is a Web app. Spotify, for instance.

Sure, I appreciate your feedback.

**Comment by cyberofficial** [comment]
> I think it's common practice for Web applications to require sign up.
> Why should it be explained?

You can just use analytical services  for user counts, and if you want to store the users info, just save the data to a file which the user can import or export.

Not 100% of people are going to use posting, following, messaging so on. It's redundant in today's already clogged social media platforms, you have a great platform, but it's major turn off for many people if you want people to sign up. 

There's no excuse to allow of a slimmed down version with the out need of a login system. Like i mentioned, you can save info to the user's local system which saves space on your end and makes the other user happy knowing their data isn't being stored somewhere else.

Your sign up process also lacks a Privacy Policy Agreement, we don't know what you are actually collecting, or sending off to 3rd party servers so on.

**Comment by staniel359** [comment]
@cyberofficial I got your point.

>You can just use analytical services for user counts

>we don't know what you are actually collecting

I think these 2 points don't match.

>and if you want to store the users info, just save the data to a file which the user can import or export.

>you can save info to the user's local system which saves space on your end

I don't get the idea of this.

>Not 100% of people are going to use posting, following, messaging so on. It's redundant in today's already clogged social media platforms, you have a great platform, but it's major turn off for many people if you want people to sign up.

But the idea is to provide full experience of using the application.
So the person should sign up to do that, even if they won't use all of its features.
If they don't want to do that, they can use other services that don't require an account.

>and makes the other user happy knowing their data isn't being stored somewhere else

>Your sign up process also lacks a Privacy Policy Agreement

Why should person be worried about their data if I don't ask for:
- Name
- Address
- Credit card info
- Phone number
- Real email (they can use fake one)
- ID info or face photo
- Other personal data only that person knows about

> we don't know what you are actually collecting, or sending off to 3rd party servers so on.

I'm not collecting or sending anything to some 3rd party services.
All the data is for app's internal use only.

**Comment by cyberofficial** [comment]
> Why should person be worried about their data if I don't ask for:
> I'm not collecting or sending anything to some 3rd party services.
You don't need to collect that, but we still don't know what you are collecting about the user if we don't have a privacy policy. 
You still need to provide one [The Data Protection Act 1998 (or DPA)] to areas outside of the USA.
We the users don't know if you collect our Geo Location Data, Computer Name, HWID, and other hardware or software info.

For all we know, you have a backend system that collects a slew of data just to resell it. Adding a policy gives most people some reassurance and reduces the shadiness. Nothing is free, and if it's free, usually means the user the is product.

I know I might be sounding rude, not trying to sound it.

There's hundreds of free sites that generate Privacy Policies as so https://www.privacypolicygenerator.info/
Can always just edit it to adjust the desireless of it.

**Comment by staniel359** [comment]
@cyberofficial Got it, thank you for clarification.
I'll add Privacy Policy.
Perhaps also Terms And Conditions would be necessary in that case.
