### ISSUE TITLE
suggestion: first use

### ISSUE THREAD

**Issue by premek** [staniel359/muffon#53]
I have just opened the app for the first time, so this is just my personal experience
When you open the application for the first time there is a screen saying: 

muffon
Welcome, username

nothing else, and most of the sections in the menu are empty: Feed, Library, even Recommendations,

It might be useful to show the user some options what to do next. Offer some popular artists or radio stations? Search bar?

**Comment by staniel359** [comment]
@premek Hello.
I was planning to add some functionality to home page, but didn't come up with it yet.

But I think all of the features are self-explanatory: feed is posts of profiles/communities you're following, library is artists/albums/tracks you're adding, and recommendations are generated based on what you've added to your library (it's mentioned [here](https://github.com/staniel359/muffon#features)). Popular artists are in Top section, radio is in Radio and search button is clearly visible.

I was expecting users to explore the app themselves.
(And I personally don't like when apps suggest me something to do.)
I don't think the app is that complicated to guide users through all the features when they're before their eyes.

But thanks for the suggestion.
I think home page should be more helpful for new users, but I don't have ideas on this question yet.
