### ISSUE TITLE
Question: Can I use your API in a personal project?

### ISSUE THREAD

**Issue by bytezeroseven** [staniel359/muffon#54]
I'm interested in the API for getting the Spotify download links. Currently, it doesn't have CORS restrictions and can be accessed from any host. Will it stay like that forever? Can your server handle a lot of requests? Let's say 100 download requests per minute without projecting much decrease in speed.

**Comment by staniel359** [comment]
@bytezeroseven Hello.

> Currently, it doesn't have CORS restrictions and can be accessed from any host. Will it stay like that forever?

> Will the spotify audio link API stay forever?

Don't know about forever :) But in further it'll be working like it's working now.

> Can your server handle a lot of requests? Let's say 100 download requests per minute without projecting much decrease in speed.

Frankly, I didn't test it that way.
Maybe the server can handle such load, but Spotify may not.
I mean, it may ban my account or something else. Don't know.
