### ISSUE TITLE
connection lost

### ISSUE THREAD

**Issue by althafpaika** [staniel359/muffon#56]
getting this error message "Connection lost
Please try again in a moment" whenever try to sign up, even though the internet is super fast

**Comment by staniel359** [comment]
@althafpaika Hello.
That's weird. The server is working.
Can you try now?

**Comment by althafpaika** [comment]
![Screenshot (6)](https://user-images.githubusercontent.com/78699910/175501098-5e99b63c-f056-4f71-8274-693237c5df58.png)
STILL SAME..

**Comment by staniel359** [comment]
@althafpaika Is it the first time you've installed it or have you installed it before?

**Comment by althafpaika** [comment]
its first time installed it..

**Comment by staniel359** [comment]
@althafpaika Which version are you using?

**Comment by althafpaika** [comment]
v0.1.0 - downloaded from the link you put on your readme.md download section (https://github.com/staniel359/muffon/releases/tag/v0.1.0)

**Comment by staniel359** [comment]
@althafpaika That's weird.
There should be language select option under signup form.
This option was added in 0.1.0.

Do you have the installer?
There should be version number in its name.
Could you check please?

**Comment by althafpaika** [comment]
@staniel359 yes i have and its name is "muffon-0.1.0-beta.1.exe"
but i can't see any language selection option in signup form �
![Screenshot (12)](https://user-images.githubusercontent.com/78699910/175940514-b3b2460f-c0ec-4820-8b45-3ccaf6dcb1d0.png)
�

**Comment by staniel359** [comment]
@althafpaika There you go.
You've downloaded wrong version, which is not working anymore.
[Here's the latest one](https://github.com/staniel359/muffon/releases/tag/v0.1.0).

**Comment by althafpaika** [comment]
@staniel359 i see, thanks its working.

**Comment by staniel359** [comment]
@althafpaika You're welcome.
