### ISSUE TITLE
hide profile / only following people and import playlist from spotify, Change default search engine

### ISSUE THREAD

**Issue by DoYouNotice** [staniel359/muffon#58]
As of now everyone can see everyones profile playlists and so on. I think this is privacy wise not really good and it would be better to hide it from everyone or only to friends/following.

It would be nice to be able to import a spotify or from other plattforms the music list so you dont have to do it manually.
i saw a feature to import data from last.fm but it didnt really work 

error: Forbidden
You don't have rights to perform this action

The default search engine is here last.fm which completely sucks for me and always gives me wrong searches.
everytime you quit the searchbar you have to manually select the search engine that you want, would be nice to be able to change that

**Comment by staniel359** [comment]
@DoYouNotice Hello.
Thanks for the feedback.

> i saw a feature to import data from last.fm but it didnt really work
error: Forbidden
You don't have rights to perform this action

You should make your scrobbles public during import.

**Comment by DoYouNotice** [comment]
> @DoYouNotice Hello. Thanks for the feedback.
> 
> > i saw a feature to import data from last.fm but it didnt really work
> > error: Forbidden
> > You don't have rights to perform this action
> 
> You should make your scrobbles public during import.

thanks for tip it worked.
btw nice update, make sure to not get copyright problems for the offline listening future

**Comment by staniel359** [comment]
@DoYouNotice Thanks.
Offline tracks are encoded, so I hope that'll do.

**Comment by staniel359** [comment]
@DoYouNotice
> It would be nice to be able to import a spotify or from other plattforms the music list so you dont have to do it manually.
i saw a feature to import data from last.fm but it didnt really work

Related to #55.
