### ISSUE TITLE
let the user copy the albums and tracks' links!

### ISSUE THREAD

**Issue by eriksenmarshal** [staniel359/muffon#6]
### Suggestions
create the option to copy and share the albums & tracks' links. Also make the ability to create playlists and also downloading for offline listening. also let users clear search history and cache.
thx for creating this app.

**Comment by staniel359** [comment]
@eriksenmarshal Thanks for the feedback.
These are planned features which will be implemented in future.

**Comment by eriksenmarshal** [comment]
Thx 🥂

**Comment by staniel359** [comment]
@eriksenmarshal 

> and also downloading for offline listening

Is this still relevant? What's the purpose of offline listening?

**Comment by eriksenmarshal** [comment]
> @eriksenmarshal
> 
> > and also downloading for offline listening
> 
> Is this still relevant? What's the purpose of offline listening?

i think it's just a good feature like spotify, for the times we dont have access to internet we can listen to music offline from our current playlist

**Comment by eriksenmarshal** [comment]
i also highly suggest to enable users copy links of songs or playlists then we can share our playlists with others... or just use links from their sources like spotify, deezer, tidal ...
