### ISSUE TITLE
Installers

### ISSUE THREAD

**Issue by jamescalderon** [staniel359/muffon#61]
I am trying to install this, but get dependency errors no matter way I try - both on Ubuntu LTS and Mint.

Please clarify/create documentation for others to simplify the installation. Running the installation as directed (or from the .deb file), even when each dependency is installed gives errors. 

This is amazing work and it would be great if it was easier to install - it would then become VERY popular. IMHO if versions are made for the major Linux distros and an AppImage made, it would be easier.

Thank you!

**Comment by staniel359** [comment]
@jamescalderon Hello.
I don't understand, are you trying to install or to build?
