### ISSUE TITLE
Why does it use some external API instead of connecting to the streaming providers directly?

### ISSUE THREAD

**Issue by mYnDstrEAm** [staniel359/muffon#62]
From [this file](https://github.com/staniel359/muffon/blob/main/src/main.js), it looks like some API is used. Why is that?

I don't think the similar music player [Nuclear](https://github.com/nukeop/nuclear/) (still very bugged) uses such and people on reddit raised concerns over this in multiple threads like [this one](https://www.reddit.com/r/javascript/comments/ogwzja/muffon_desktop_music_browser/). Why aren't you only connecting to the streaming providers' APIs instead and manage all the other things locally in the code?

**Comment by staniel359** [comment]
@mYnDstrEAm Hello.
It's back-end part of the application.
It manages not only music streaming logic, but also data processing and formatting, database reading and writing, background jobs, and contains secret data (like API keys).

**Comment by mYnDstrEAm** [comment]
* Is the backend open source too?
* I still don't understand why the music streaming logic, data processing and formatting, database reading and writing and background jobs aren't simply done locally by the client.
* Can't the API keys be generated/stored locally? Does somebody know how Nuclear does this? From [this file](https://github.com/nukeop/nuclear/blob/6a99b3f85042f170de840d3e9b9381d8cd5fd84b/packages/app/app/globals.js) it seems like the API keys are stored locally in Nuclear ([example](https://github.com/nukeop/nuclear/blob/00c726048b60eefcacc74977f3f7e212a5b81337/packages/core/src/rest/Soundcloud.ts)) or is that app also connecting to some external API?

Otherwise, this seems like a great app, so I'd really like to try it and already [requested a firejail profile](https://github.com/netblue30/firejail/issues/1139#issuecomment-1236083911) for it so that it can be easily sandboxed.

**Comment by staniel359** [comment]
@mYnDstrEAm 
> Is the backend open source too?

Sure, the source code is [here](https://github.com/staniel359/muffon-api).

> I still don't understand why the music streaming logic, data processing and formatting, database reading and writing and background jobs aren't simply done locally by the client.

> Can't the API keys be generated/stored locally? Does somebody know how Nuclear does this? From [this file](https://github.com/nukeop/nuclear/blob/6a99b3f85042f170de840d3e9b9381d8cd5fd84b/packages/app/app/globals.js) it seems like the API keys are stored locally in Nuclear ([example](https://github.com/nukeop/nuclear/blob/00c726048b60eefcacc74977f3f7e212a5b81337/packages/core/src/rest/Soundcloud.ts)) or is that app also connecting to some external API?

You may read about [SSOT](https://en.wikipedia.org/wiki/Single_source_of_truth) concept.

**Comment by mYnDstrEAm** [comment]
Well that makes sense but still all of this could be done locally within the client.

This way, you don't need to run a server, people don't need to send info to some server or be dependent on it, and the streaming services get accessed by the users themselves, etc. I don't see how this would be either required or better than not having to connect to some intermediary server.

**Comment by staniel359** [comment]
@mYnDstrEAm Look, the app is not just about music listening.
It has a lot of other features that could not be done without remote server.
That's how web applications work.
Most of the things are just impossible to do just on the client side.

**Comment by staniel359** [comment]
@mYnDstrEAm What to Nuclear: maybe it does have all the needed logic on client side and doesn't need back-end server for working.
