### ISSUE TITLE
No support for surround audio

### ISSUE THREAD

**Issue by filipporomani** [staniel359/muffon#67]
I have a 5.1 surround, and i'm not able to use that with muffon!
That's the only negative perk of the software.
I hope it can get fixed!

**Comment by staniel359** [comment]
@filipporomani Hello again and thanks for your feedback.
Are you sure that the audio you're listening on muffon is in 5.1?

**Comment by filipporomani** [comment]
Hello to you too!
Yes I'm sure, I play the same song on Spotify and i have full surround, and with the same song on muffon it hasn't.

**Comment by staniel359** [comment]
@filipporomani I see.
Can you provide a song example?

**Comment by filipporomani** [comment]
For example glimmer of hope by Tevvez
In spotify app i get full surround, in muffon i don't

**Comment by staniel359** [comment]
@filipporomani Do you use Spotify premium account or basic?

**Comment by filipporomani** [comment]
Basic

**Comment by staniel359** [comment]
@filipporomani I made a research on your question.
Turns out that there're some problems with 5.1 sound on Chromium-based browsers (Electron / Chrome / Edge).
Whereas Firefox plays it fine.

Didn't find much information on how to solve this.
If there're some info, it's outdated now.

**Comment by filipporomani** [comment]
Ok, hope Google will document it!
Anyways, thank you for the help!

**Comment by gamersi** [comment]
@staniel359 i saw your issue(https://github.com/electron/electron/issues/35853) and i just found a new flag which is supposed to work with chrome versions after 79(newer versions:
--disable-features=AudioServiceOutOfProcess 
https://boomspeaker.com/google-chrome-5-1-surround-sound/
this article was updated 9 days ago so I suppose it is currently working
hope this helps

**Comment by staniel359** [comment]
@gamersi Thanks.

I use this site to test 5.1 audio:
https://www2.iis.fraunhofer.de/AAC/multichannel.html

I tried using that flag, but the sound hasn't changed.
But I can't really tell if sound in Electron is actually 5.1.
There seems to be an issue with right surround speaker.
Also I have quite poor headphones so I can't check it properly.

**Comment by filipporomani** [comment]
the real problem for this is that some providers don't provide 5.1 music! As far as i know, YouTube only provides stereo audio with no surround. 
Instead spotify provides up to 7.1 audio

**Comment by filipporomani** [comment]
On brave (chromium) i can play 5.1 audio without any particular config.

**Comment by staniel359** [comment]
@filipporomani I've tried the Brave browser and the issue is the same as I wrote [above](https://github.com/staniel359/muffon/issues/67#issuecomment-1383192054).
How do you tell if audio is 5.1 or not?

**Comment by filipporomani** [comment]
I actually have a subwoofer and 2 rear speakers, with spotify both of them play while with muffon they don't

**Comment by filipporomani** [comment]
i don't what it depends from, on firefox for example everything (even youtube) is surround, on brave only the link you sent above plays with surround.

**Comment by staniel359** [comment]
@filipporomani I see.

I may try making some code changes, then release the next version and then you test it and tell me if it worked, okay?

**Comment by filipporomani** [comment]
Yes ofc! I'll wait for the next release

**Comment by staniel359** [comment]
@filipporomani Are you using Windows?

**Comment by filipporomani** [comment]
Yes I'm using windows

Il mar 7 feb 2023, 10:06 Aleksey Shpakovsky ***@***.***> ha
scritto:

**Comment by staniel359** [comment]
@filipporomani Try this please:
1. Right click on muffon's shortcut
2. `Properties`
3. Target field

Like here:

![image](https://user-images.githubusercontent.com/18214933/217282519-55b4beee-792a-47b2-9499-893d5406a1aa.png)

5. Try adding those lines at the end, one at a time, then all of them:
```
--disable-features=AudioServiceOutOfProcess
--disable-features=AudioProcessSandbox
--disable-features=AudioServiceSandbox
--try-supported-channel-layouts
--force-wave-audio
--disable-audio-output-resampler
```
6. Test surround audio

**Comment by filipporomani** [comment]
Okk so today I'll not be home until 22PM (UTC+2), I'll probably test later
this evening or tomorrow.

Thank you so much and sorry!!

Il mar 7 feb 2023, 16:11 Aleksey Shpakovsky ***@***.***> ha
scritto:

**Comment by staniel359** [comment]
@filipporomani Please don't be sorry :)

**Comment by filipporomani** [comment]
--try-supported-channel-layouts worked for me. Now 5.1 works!!! At least on my machine

**Comment by staniel359** [comment]
@filipporomani Good.
Only this one worked?

**Comment by filipporomani** [comment]
Yes

**Comment by filipporomani** [comment]
Btw, audio lags heavily sometimes using that flag

**Comment by staniel359** [comment]
@filipporomani Okay, thank you!

How exactly?

**Comment by filipporomani** [comment]
Nvm, it probably was a problem of my cable. It was lagging with spotify too, i changed audio cable and now it works.

**Comment by staniel359** [comment]
@filipporomani Good.
Now I need to figure out how to add this flag to packaged app.

**Comment by filipporomani** [comment]
I really can't help you with that, i don't know how to package an app

**Comment by filipporomani** [comment]
The only thing i miss the most is the spotify favourites list, is there anyway i can import it or should i add tracks manually?

**Comment by staniel359** [comment]
@filipporomani Right now there's no Spotify account integration yet, but it's planned.

**Comment by filipporomani** [comment]
Good! Thx!

**Comment by staniel359** [comment]
@filipporomani @DoYouNotice I've released a new version.
Could you try it now?

**Comment by filipporomani** [comment]
Should I remove the flag before trying?

**Comment by filipporomani** [comment]
IT WORKSSS

**Comment by filipporomani** [comment]
Good job mate! It works fine without even adding a flag!

**Comment by filipporomani** [comment]
Now the only missing thing (for me at least) is the spotify favourites and playlists import. 
Unluckily I cannot code in JS, if I could I would have helped with that.

**Comment by staniel359** [comment]
@filipporomani Good, thank you.

Don't worry, Spotify account integration is a planned feature.
