### ISSUE TITLE
Create a Discord, Revolt, Matrix, or Mattermost server, so we can talk to you (the devs) casually

### ISSUE THREAD

**Issue by candroid-man** [staniel359/muffon#70]
Discord would be the best option for convenience, since even most Linux users use Discord, but it is not very private.
[Revolt](https://revolt.chat/) is a FOSS Discord clone that could work well
Matrix would be the most private but wouldn't support multiple chats within one place
Mattermost is best for development and direct integration with GitHub for issues and to chat with people

No matter what you pick, you should pick one. I like to know who's behind a project a little more personally

**Comment by staniel359** [comment]
@candroid-man Hello.
Okay, I've created Discord server:
https://discord.gg/kpWsA5NBmJ

**Comment by candroid-man** [comment]
Could you create a permanent link? That link seems to have already expired

**Comment by candroid-man** [comment]
Ignore that I'm stupid
