### ISSUE TITLE
Есть идея

### ISSUE THREAD

**Issue by Alexey-Yoshimitsu** [staniel359/muffon#74]
Предлагаю сделать отдельную версию приложения на tauri, так как electron достаточно много потребляет ресурсов. Я бы сделал сам отдельную ветку, но я плохо понимаю ваш код. Было бы неплохо если бы вы по подробнее объяснили что происходит при работе приложения и тд. Так же я был бы рад поучаствовать в разработке. Как говориться: "Чем смогу тем помогу".

**Comment by staniel359** [comment]
@Alexey-Yoshimitsu Приветствую.

Только недавно узнал про Tauri и хотел перейти на него, но есть несколько нюансов:

Во-первых, совсем не знаю Rust.

А во-вторых, не похоже, что получится реализовать систему вкладок, поскольку Tauri не имеет аналога `BrowserView` из Electron'а, который сейчас для этого используется в muffon'е.

Где-то было сказано, что в отличие от Electron'а, который является по сути настраиваемым браузером на движке Chromium, Tauri - лишь обёртка системного браузерного движка, который, наверняка, вряд ли получится настроить.

Была идея сделать вкладки через подобие iframe'ов на уровне Vue или через что-то похожее, но пока не придумал, как.

Так что пока, видимо, придётся оставаться на Electron'е.

(Я бы не сказал, что он слишком уж много ресурсов потребляет.
Если брать конкретно muffon, то во всяком случае не больше, чем обычный браузер).

А как бы Вы хотели поучаствовать в разработке?

**Comment by Alexey-Yoshimitsu** [comment]
Мне было бы интересно
