### ISSUE TITLE
UI bug on macOS

### ISSUE THREAD

**Issue by gamersi** [staniel359/muffon#77]
It looks good on windows but when i run it in macOS(no matter if i run your release or build from source) the tabs on the top are cut off:
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/46320904/202250398-3ac59e86-5942-4b16-a9fa-86b2437af9c1.png">

**Comment by staniel359** [comment]
@gamersi Hello again.
Does this happen both on maximized and non-maximized window?

**Comment by gamersi** [comment]
yes. but if i maximize it **and** press cmd + R then it reloads and fixes itself but only when it is in fullscreen

**Comment by gamersi** [comment]
if you want i can send you a video via email

**Comment by staniel359** [comment]
@gamersi Yes, please.
staniel359@gmail.com

**Comment by gamersi** [comment]
I sent it to you(sigamer805@gmail.com)

**Comment by staniel359** [comment]
@gamersi Thank you.
That's weird.
Will try to figure this out.

**Comment by staniel359** [comment]
@gamersi One question.
Does this also happen with packaged app?

**Comment by staniel359** [comment]
@gamersi Does this happen on app start or after window resize?

**Comment by gamersi** [comment]
On App Start
MacBook Pro 2019
macOS Ventura

**Comment by staniel359** [comment]
@gamersi I see.
Too bad I don't have a Mac to test this bug.

Could you try installing earlier versions of the app and see when the bug starts to happen?
Maybe it is related to Electron version update.

**Comment by gamersi** [comment]
I am going to try it now and will tell you the result of my research

**Comment by gamersi** [comment]
Ok, I just tried version 2.0 and there were no such issues. it appears to affeact only version 3 and above. 
And I just want to say that you should probably include a uninstaller for macos, bekause pkgs can be tricky to delete(I had to use AppCleaner to remove everything so that it could be reinstalled)

**Comment by staniel359** [comment]
@gamersi Thanks for the hint.

There will be `.dmg` installer for the next version.
Are they easier to uninstall?

**Comment by gamersi** [comment]
> @gamersi Thanks for the hint.
> 
> 
> 
> There will be `.dmg` installer for the next version.
> 
> Are they easier to uninstall?

I would think so but could make problems with incompatible local data I think

**Comment by staniel359** [comment]
@gamersi How do you usually uninstall apps on Mac and what extensions do installers have?

**Comment by gamersi** [comment]
There are 3 common types of "installers"

- Dmg: most popular, it has the packaged app as zip(number 3) and a reference to the applications folder. You simply drag the application to the referenced folder. To uninstall, you simply delete the zip(.app) out of the applications folder in the most cases
- pkg: executable, kinda like a windows installer. Uninstalled must be manually provided unless the app does not use local storage, then it could theoretically be uninstalled in the applications folder just like the other ones
- zip's(.app is shown in files): the content of dmgs, but it is not as convenient as dmg

This could give a few more info:
https://apple.stackexchange.com/questions/383730/how-do-you-uninstall-pkg-file

https://www.reddit.com/r/MacOS/comments/fmcfsh/dmg_pkg_and_zip_differences/

https://superuser.com/questions/604607/differences-between-dmg-and-various-zip-like-formats

But I can just speak from my experience as I just use Mac for my laptop not as my desktop os

**Comment by staniel359** [comment]
@gamersi Got it, thank you.

Will try to fix the bug.

**Comment by staniel359** [comment]
@gamersi I've made changes.
Could you test them on your system?

**Comment by gamersi** [comment]
I just downloaded the newest src and I think isMac is not getting initialized properly:

A JavaScript error occurred in the main process
Uncaught Exception:
ReferenceError: isMac is not defined
at create (/Users/simon/Documents/code/muffon/electron/actions/tab/create.js:73:26)
at IpcMainImpl.handleAddTab (/Users/simon/Documents/code/muffon/electron/handlers/ipc/tab.js:24:3)
at IpcMainImpl.emit (node:events:527:28)
at EventEmitter.<anonymous> (node:electron/js2c/browser_init:165:11237)
at EventEmitter.emit (node:events:527:28)

**Comment by staniel359** [comment]
@gamersi Oops, sorry.

**Comment by gamersi** [comment]
It works fine now, but if you start/refresh it in fullscreen there is a bit too much spacing 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/46320904/202554747-24e240b0-eb45-4aa0-b898-ea467a6a2d5b.png">

**Comment by staniel359** [comment]
@gamersi I see.
Could you send me a video of this behavior?
(You can attach it here).

**Comment by gamersi** [comment]
unfortunately, the video is 40MB and the size limit on github is 10MB. I am going to send it via email as I already did yesterday

**Comment by gamersi** [comment]
sent it

**Comment by staniel359** [comment]
@gamersi Thank you.
I've made changes.
Could you check?

**Comment by gamersi** [comment]
it works like a charm now.
Thanks

**Comment by staniel359** [comment]
@gamersi Thank you for your help.
