### ISSUE TITLE
[Feature] Can we please add Plex?

### ISSUE THREAD

**Issue by arsaboo** [staniel359/muffon#82]
As the title says, it would be great to have Plex integration. I have a ton of music that is not available on any streaming platform. Plex has a well-developed [API](https://github.com/pkkid/python-plexapi) and will be a great music source.

**Comment by staniel359** [comment]
@arsaboo Hello.
On Plex's site I see that it depends on Tidal.
How is it related to your own music collection?

**Comment by arsaboo** [comment]
Plex works with your own music files. You can add Tidal if you want, but it is not required. If you add Tidal, it can pull music from both sources. In fact, most users use Plex with their own music files with Plexamp (their music focused app). Hope that clarifies.

**Comment by arsaboo** [comment]
See this https://www.reviewgeek.com/114946/how-to-create-your-own-music-streaming-service-with-plex/amp/ for an overview. You can set up Plex even on a Pi.

**Comment by staniel359** [comment]
@arsaboo So can I search for and listen to your audio?

**Comment by arsaboo** [comment]
If anyone shares their server with you, then you can search and listen to their audio. In that sense, it is a great substitute for traditional streaming services. You can obviously host your own music.

**Comment by staniel359** [comment]
@arsaboo So it's actually not in the global access, making it impossible to search for or listen to?

**Comment by arsaboo** [comment]
No....the tracks are not global. It is not a streaming service with its own library of songs. It is software that allows users to make their own library available for streaming.

**Comment by staniel359** [comment]
@arsaboo I see.
Well, Im sorry, but muffon works only with global access sources for reliability.
But I'm sure Plex is a good service.
