### ISSUE TITLE
No program specific audio control

### ISSUE THREAD

**Issue by algebuckina** [staniel359/muffon#83]
The current system uses windows audio to change the volume of music. I'd love to see a feature that lets the audio of the program work uncoupled from the system audio like other music players.

**Comment by staniel359** [comment]
@algebuckina Hello.
There's already a voulme control popup on player panel.
Or you mean adding key combination to control the app volume?

**Comment by algebuckina** [comment]
Ah, okay the slider doesn't work on my end. Running windows 10.

**Comment by staniel359** [comment]
@algebuckina It's a known bug.
The fix will be released in the next version.
