### ISSUE TITLE
Muffon skips tracks

### ISSUE THREAD

**Issue by LolloLomb** [staniel359/muffon#88]
Hi from Italy! First of all, thanks for your amazing work, it's fantastic.
With the new update i've encountered some issues playing tracks. For example this morning i was listening to Souvlaki by Slowdive.
So, if i select a track, it plays correctly (so it is in the server), but if the same track comes after another song, it plays for 1-2 sec and then skip to the next. I've encountered this problem with every album/song/artist i tried with. I can listen to a song, the second one skip, the third one plays, the fourth skip and so on... this happens if i put a song in queue too, not only if a select an album to listen to

Anyone has the same problem? Anyone solved it?

**Comment by staniel359** [comment]
@LolloLomb Hello.
It's a known bug and the fix will be released in the next version.

**Comment by LolloLomb** [comment]
Thanks for the quick response and thanks again for your work
Have a nice day!

**Comment by staniel359** [comment]
@LolloLomb Thanks, you too!
And thank you for nice words :)
