### ISSUE TITLE
Scrobble feature

### ISSUE THREAD

**Issue by Araken** [staniel359/muffon#9]
Are there any plans to add a scrobble feature to Muffon? Thank you.

**Comment by staniel359** [comment]
@Araken I'm not planning it right now, but let's see in the future.
If there's a need for that, then sure, why not.

**Comment by starise** [comment]
it'd be a nice feature

**Comment by staniel359** [comment]
@Araken @starise Do you want the tracks to be scrobbled only to Last.FM or to muffon as well?

**Comment by starise** [comment]
@staniel359 I was talking about sending tracks infos from muffon player to audioscrobbler APIs (last.fm/libre.fm) for tracking. Maybe I didn't understand: what do you mean with 'to muffon' ?

**Comment by staniel359** [comment]
@starise I meant, should they be tracked in app too.
But I got you, only Last.FM.
