### ISSUE TITLE
Digital surround sound from Logitech software gets applied to Muffon

### ISSUE THREAD

**Issue by DoYouNotice** [staniel359/muffon#91]
I have Headphones from Logitech and when i am using there 
surround sound feature. Which is only applied in games for better surround, 
It gets applied for Muffon and it sounds terrible. It Dosent apply to Spotify or Youtube or other things.

**Comment by staniel359** [comment]
@DoYouNotice Hello.
Unfortunately, I don't have such headphones so I can't test it.

Is it applied automatically?
Can you add muffon to this feature's exceptions?

**Comment by DoYouNotice** [comment]
Yes it is applied automatically. there is only one feature which lets me add profiles for a app. so i can add muffon to it and say that
if muffon is turned on, the entire digital sorround sound turns off. it also only works if muffon is the tab i am actively on. if it is in the background the feature will not apply. so basically useless because
A it turns off the entire sorround sound
B does not work in the background

edit: Probably has to do something with multi channel audio. I think it would work fine if it would use stereo, based on what it says:
the surround sound mode used will depend on the output of your content. Multichannel content will use the selected multi channel mode, and stereo content will use the super stereo mode

**Comment by staniel359** [comment]
@DoYouNotice I see.
So you mean it's somehow related to [this](https://github.com/staniel359/muffon/issues/67)?

**Comment by DoYouNotice** [comment]
not sure if that is related. I think the app is build a little bit different and does not use the normal audio that other app uses.
i have tried and build the dev build with your fix and it does not work.

**Comment by staniel359** [comment]
@DoYouNotice I need to investigate this then.

**Comment by staniel359** [comment]
@DoYouNotice Are you using Windows?

**Comment by DoYouNotice** [comment]
@staniel359 yes

**Comment by staniel359** [comment]
@DoYouNotice Could you try [this](https://github.com/staniel359/muffon/issues/67#issuecomment-1420935927)?

**Comment by DoYouNotice** [comment]
@staniel359 alright this one works --try-supported-channel-layouts

**Comment by staniel359** [comment]
@DoYouNotice Good, thank you!

So this one is related to [this](https://github.com/staniel359/muffon/issues/67) issue.
I'll close this one then.
