### ISSUE TITLE
Support for Apple silicon processors

### ISSUE THREAD

**Issue by aghilpadash** [staniel359/muffon#94]
in future release Support for Apple silicon processors

**Comment by staniel359** [comment]
@aghilpadash Hello.
Sorry, I don't understand how it is related.

**Comment by gamersi** [comment]
He wants the future versions to run on apple silicon (M1/2) processors. you can read more about this here: https://www.electronjs.org/blog/apple-silicon/

**Comment by staniel359** [comment]
@gamersi Thanks.

So basically there should be an installer for `arm64` processor?

**Comment by gamersi** [comment]
> @gamersi Thanks.
> 
> 
> 
> So basically there should be an installer for `arm64` processor?

Correct!

**Comment by staniel359** [comment]
@aghilpadash @gamersi No problem.
