### ISSUE TITLE
Cannot remove songs from "Saved tracks"

### ISSUE THREAD

**Issue by SenorGeese** [staniel359/muffon#98]
![1197-4](https://user-images.githubusercontent.com/87151598/222039927-9a444215-e97a-48ff-8739-d65a05dc25f0.png)

---

![1198-3](https://user-images.githubusercontent.com/87151598/222039977-36ef3cf8-bc87-4698-9a8b-42ef08a9e251.png)

---

![1199-8](https://user-images.githubusercontent.com/87151598/222040059-d1442ee1-a357-4b5e-9764-4c64edb99395.png)

---

I can't find an option to remove songs from my "Saved tracks" list. Am I missing the button or is this a missing feature?

Thank you for the great app!

**Comment by staniel359** [comment]
@SenorGeese I'm sorry, that's actually a mistake of mine.
When logged in, the "Delete" option is present. In anonymous mode it isn't.
The fix will be released in the next version.
