### ISSUE TITLE
Not scrobbling tracks with Spotify

### ISSUE THREAD

**Issue by jbwharris** [staniel359/muffon#99]
I listened to a few tracks in muffon and for some reason they wouldn't scrobble. I'm using macOS 13.3. It would show the scrobble on last.fm as now playing, but when it came time to actually record the scrobble, it would just skip it.

**Comment by staniel359** [comment]
@jbwharris Hello.
What's your nickname on muffon?

**Comment by jbwharris** [comment]
Same as GitHub, @jbwharris

**Comment by staniel359** [comment]
@jbwharris And your `Scrobbling` option is enabled?

**Comment by staniel359** [comment]
@jbwharris Thanks.

That's weird. Need to investigate this one.

**Comment by jbwharris** [comment]
Here's my last.fm settings
![image](https://user-images.githubusercontent.com/2962327/229914498-1c204aa3-ff7a-4ba7-af49-047f22d40a02.png)

Now scrobbling showing in last.fm only showed up after 50% of the song played, but didn't actually scrobble once that 50% was hit.
![image](https://user-images.githubusercontent.com/2962327/229916409-be84c2fe-47cc-4655-a7ff-9991386c918a.png)

100% of the song plays in radio and for whatever reason it didn't go to the next track and you can see the now scrobbling track has just disappeared instead of actually recording the scrobble. 
![image](https://user-images.githubusercontent.com/2962327/229917106-beb29f76-3101-4aff-8de7-9a763f581225.png)

**Comment by jbwharris** [comment]
I just played around with the length setting and changed it to 75% and it seems to have scrobbled once, but only once. I tried changing it to 25% and back to 50% and it still isn't working. Also, is the radio supposed to autoplay? I can only get it to play one song, then need to hit next to get it to play another song.

**Comment by staniel359** [comment]
@jbwharris Thanks for the information.

There was an actual bug in application when audio progress wasn't being tracked.
The fix will be released in the next version.

> Also, is the radio supposed to autoplay?

Actually right now it isn't, but it should, of course. I'll add this feature.
Thanks for the idea.
